apiVersion: v1
kind: BuildConfig
metadata:
  name: basic-servlet-example-dockerfile-binary
  labels:
    app: basic-servlet-example
spec:
  output:
    to:
      kind: DockerImage
      name: nexus-container-registry-nexus.apps.cluster-3bcb.sandbox1869.opentlc.com/myapps/basic-servlet-example-s2i:latest
    # The pushSecret is optional, pullSecret is being used for push by default.
    pushSecret:
      name: nexus-container-registry-nexus

  source:
    type: Binary
    binary: {}
    dockerfile: |-
      FROM overwritten-from-strategy-field
      COPY *.war /deployments/

  strategy:
    type: Source
    dockerStrategy:
      from:
        kind: DockerImage
        name: nexus-container-registry-nexus.apps.cluster-3bcb.sandbox1869.opentlc.com/jboss-webserver-5/webserver54-openjdk11-tomcat9-openshift-rhel8:latest
      # A pull secret must be created and added to the build. Linking to ServiceAccount "builder" '--for=mount' also works.
      pullSecret:
        name: nexus-container-registry-nexus