apiVersion: v1
kind: BuildConfig
metadata:
  name: basic-servlet-example-dockerfile-binary
  labels:
    app: basic-servlet-example
spec:
  output:
    to:
      kind: DockerImage
      # Global pull secret doesn't work. Linking to SA builder '--for=mount' works.
      name: nexus-container-registry-global-pull-nexus.apps.cluster-ccf2.sandbox801.opentlc.com/basic-servlet-example-s2i:latest
    # pushSecret:
      # name: nexus-container-regis try-global-pull-nexus

      # name: nexus-container-registry-nexus.apps.cluster-ccf2.sandbox801.opentlc.com/basic-servlet-example-s2i:latest
      # pushSecret is optional, pullSecret is being used for push too
    # pushSecret:
      # name: nexus-container-registry-nexus

  source:
    type: Binary
    binary: {}
    dockerfile: |-
      FROM overwritten-from-strategy-field
      COPY *.war /deployments/
  strategy:
    type: Source
    dockerStrategy:
      from:
        kind: DockerImage
        # Global pull secret works
        # name: nexus-container-registry-global-pull-nexus.apps.cluster-ccf2.sandbox801.opentlc.com/jboss-webserver-5/webserver54-openjdk11-tomcat9-openshift-rhel8:latest
        
        # A docker pull secret must be created and added to the build. Linking to SA builder '--for=mount' also works.
        name: nexus-container-registry-nexus.apps.cluster-ccf2.sandbox801.opentlc.com/jboss-webserver-5/webserver54-openjdk11-tomcat9-openshift-rhel8:latest
      # pullSecret:
        # name: nexus-container-registry-nexus