apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: fuse7hello
  labels:
    app: fuse7hello
spec:
  selector:
    app: fuse7hello
  replicas: 1
  template:
    metadata:
      labels:
        app: fuse7hello
    spec:
      containers:
        - name: fuse7hello-ui
          image: nexus-container-registry-nexus.apps.cluster-3bcb.sandbox1869.opentlc.com/test/fuse7hello:latest
          ports:
            - containerPort: 8080
            - containerPort: 8778
            - containerPort: 9779
          resources: {}
          imagePullPolicy: Always