apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: fuse7hello
  name: fuse7hello
spec:
  lookupPolicy:
    local: true
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: nexus-container-registry-nexus.apps.cluster-ccf2.sandbox801.opentlc.com/test/fuse7hello:latest
    referencePolicy:
      type: Local