apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: fuse7hello
spec:
  selector:
    app: fuse7hello
  replicas: 1
  template:
    metadata:
      labels:
        app: fuse7hello
    spec:
      containers:
        - name: fuse7hello-ui
          image: 'ignored'
          ports:
            - containerPort: 8080
            - containerPort: 8778
            - containerPort: 9779
          resources: {}
          imagePullPolicy: Always
      serviceAccountName: default
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: false
        containerNames:
          - fuse7hello-ui
        from:
          kind: ImageStreamTag
          name: fuse7hello:latest
      type: ImageChange